		</td>
	</tr>
</table>
<br>
<br>
<?php
																																																				if ($file) {
	?>
<table width="400" border="1" cellpadding="5">
    																																										<tr valign="top">
        <td colspan="3">
				            <b>	Beispiel-Erklärung:</b>
				        </td>
				    </tr>
				    <tr>
				        <td colspan="3">
					           <font color="#008000">
                <b>info1004.pdf</b>
           </font>
        </td>
    </tr>
    <tr>
        <td>
            <font color="#008000">
                <b>info</b>
            </font>
             = Fach
        </td>
        <td>
            <font color="#008000">
                <b>1</b>
            </font>
             = 1. Semester
        			</td>
        			<td>
            		<font color="#008000">
                <b>004</b>
            </font>
             = Übungsblatt 4
        			</td>
    			</tr>
    			<tr>
        			<td colspan="3">
            			<b>Fächer:</b>
        			</td>
    			</tr>
    			<tr>
        			<td>
            			<font color='#E60000'><b>info</b></font>
        			</td>
        			<td colspan="2">
        				    Informatik I
        				</td>
    				</tr>
    <tr>
        <td>
            <font color='#E60000'><b>ti</b></font>
        </td>
        <td colspan="2">
            Technische Informatik I
        </td>
    </tr>
    <tr>
        <td>
            <font color='#E60000'><b>m</b></font>
        </td>
        <td colspan="2">
            Mathe I für Informatik und Bioinformatik
        </td>
    </tr>
			</table>
		
<?php
}
?>
		
</ul>
&copy; <a href="http://i-wars.net/" target="_blank">www.i-wars.net</a><br>
&copy; <a href="http://blog.bloca.de/" target="_blank">blog.bloca.de</a>
</body>
</html>