<html>
<head>
<LINK REL=StyleSheet HREF="<?php $abs; ?>/studium/style.css" TYPE="text/css">
<title>juuro.projects</title>
</head>
<body>
<h2>juuro.projects:</h2>
An dieser Stelle werde ich meine ganzen PHP-Projekte und -Dateien veröffentlichen. Bei Klick auf das Projekt oder die Datei öffnet es sich in einem neuen Fenster!
<ul>
<table width="1000" cellpadding="5" border="1">
	<tr valign="top">
		<td>